language: ruby
dist: bionic
cache: bundler
rvm:
  - 2.6.3
branches:
  only:
    - travis-ci
env:
  global:
    - PGPORT=5433
    - JAVSCRIPT_DRIVER=headless_chrome
    - DB_NAME_TEST=pupilfirst_test
    - DB_USERNAME=postgres
    - DB_HOST=localhost:5433
services:
  - postgresql
addons:
  postgresql: "11"
  chrome: stable
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
before_script:
  - psql -c 'create database pupilfirst_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
